services:
  nginx-deusops:
    build: .
    ports:
      - "10002:8080"
    tty: true
    stdin_open: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro